# This is a basic workflow to help you get started with Actions
name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_COMPUTED_GOTOS=OFF
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: build
      run: |
        cd build
        msbuild -m jstar.sln
