# This is a basic workflow to help you get started with Actions
name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DUSE_COMPUTED_GOTOS=OFF
    - name: build
      run: |
        cd build
        MSBuild.exe jstar.sln
