# This is a basic workflow to help you get started with Actions
name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_COMPUTED_GOTOS=OFF -DCMAKE_INSTALL_PREFIX=build/release/jstar
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: build
      run: |
        cd build
        msbuild -m jstar.sln
    - name: package binaries
      run: |
        cd build
        mkdir -p release/jstar
        msbuild INSTALL.vcxproj
        cp "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\*\x64\msvcp140.dll" release/jstar/bin
        cp "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\*\x64\vcruntime140.dll" release/jstar/bin
        cp "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\*\x64\vcruntime140_1.dll" release/jstar/bin
    - name: upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: jstar-x64-windows
        path: build/release/jstar

